var bingoList = [];
bingoList[1] = [
  { name: "LSV scroll wheel", types: ["normal"]},
  { name: "Drafting UW Control", types: ["normal"]},
  { name: "500 Pauls in one day", types: ["normal"]},
  { name: "T-Shirt ad", types: ["normal"]},
  { name: "Strawpoll", types: ["normal"]},
  { name: "MODO Crashes", types: ["normal"]},
  { name: "LSV Skypes in", types: ["normal"]},
  { name: "Paul gets trolled", types: ["normal"]},
  { name: "&quot;Was that good?&quot;", types: ["normal"]},
  { name: "Money draft", types: ["normal"]},
  { name: "Made the finals", types: ["normal"]},
  { name: "Double queueing", types: ["normal"]},
  { name: "Eating on stream", types: ["normal"]},
  { name: "K-pop", types: ["normal"]},
  { name: "Lisa shows up", types: ["normal"]},
  { name: "Kyle climbs on Paul", types: ["normal"]},
  { name: "Cheon rankings are linked", types: ["normal"]},
  { name: "A bot gets spammy", types: ["normal"]},
  { name: "Cruer Contror", types: ["normal"]},
  { name: "dududududududu", types: ["normal"]},
  { name: "Restart MODO", types: ["normal"]},
  { name: "Lose round 1", types: ["normal"]},
  { name: "Win a match 2-0", types: ["normal"]},
  { name: "Opponent gets salty", types: ["normal"]},
  { name: "Paul gets salty", types: ["normal"]},
  { name: "Record-high Paul streak", types: ["normal"]},
  { name: "Get very lucky", types: ["normal"]},
  { name: "Sick read", types: ["normal"]},
  { name: "Music with no commentary", types: ["normal"]},
  { name: "24 hour stream", types: ["normal"]},
  { name: "Cheon counter at multiple of 25", types: ["normal"]},
  { name: "Trash talking", types: ["normal"]},
  { name: "First stream in 3 days", types: ["normal"]},
  { name: "A+ Pun", types: ["normal"]},
  { name: "$50+ donation", types: ["normal"]},
  { name: "&quot;Seems good&quot", types: ["normal"]},
  { name: "&quot;Let's be realistic&quot;", types: ["normal"]},
  { name: "2000+ viewers", types: ["normal"]},
  { name: "Paul spam", types: ["normal"]},
  { name: "Hosted by someone else", types: ["normal"]},
  { name: "Chat confuses Paul", types: ["normal"]},
];

$(function() { srl.bingo(bingoList, 5); });